title: "Löth Läderhantverk"
description: "Svenskt hantverk sedan 1972"
keywords: "löth, läder, hantverk, läderhantverk, torghandel, marknad"
url: "http://www.lothlader.se"
exclude:
  - README.md
gems:
  - jekyll-sitemap
