- title: "Armband bred rem"
  category: "bracelets"
  image: "/images/products/armband-bred-rem.jpg"
  thumbnail: "/images/products/armband-bred-rem-thumbnail.jpg"

- title: "Armband bred special"
  category: "bracelets"
  image: "/images/products/armband-bred-special.jpg"
  thumbnail: "/images/products/armband-bred-special-thumbnail.jpg"

- title: "Armband flätat"
  category: "bracelets"
  image: "/images/products/armband-flatat.jpg"
  thumbnail: "/images/products/armband-flatat-thumbnail.jpg"

- title: "Bälte klassiskt"
  category: "belts"
  image: "/images/products/balte-klassiskt.jpg"
  thumbnail: "/images/products/balte-klassiskt-thumbnail.jpg"

- title: "Bälte special"
  category: "belts"
  image: "/images/products/balte-special.jpg"
  thumbnail: "/images/products/balte-special-thumbnail.jpg"

- title: "Handväska rak"
  category: "handbags"
  image: "/images/products/handvaska-rak.jpg"
  thumbnail: "/images/products/handvaska-rak-thumbnail.jpg"

- title: "Handväska rundad"
  category: "handbags"
  image: "/images/products/handvaska-rundad.jpg"
  thumbnail: "/images/products/handvaska-rundad-thumbnail.jpg"

- title: "Kreditkortshållare"
  category: "wallets-creditcard-holders"
  image: "/images/products/kreditkortshallare.jpg"
  thumbnail: "/images/products/kreditkortshallare-thumbnail.jpg"

- title: "Mobilfodral för bälte"
  category: "covers"
  image: "/images/products/mobilfodral-for-balte.jpg"
  thumbnail: "/images/products/mobilfodral-for-balte-thumbnail.jpg"

- title: "Nyckelfodral"
  category: "covers"
  image: "/images/products/nyckelfodral.jpg"
  thumbnail: "/images/products/nyckelfodral-thumbnail.jpg"

- title: "Plånbok stor"
  category: "wallets-creditcard-holders"
  image: "/images/products/planbok-stor.jpg"
  thumbnail: "/images/products/planbok-stor-thumbnail.jpg"

- title: "Träsko klassisk"
  category: "clogs"
  image: "/images/products/trasko-klassisk.jpg"
  thumbnail: "/images/products/trasko-klassisk-thumbnail.jpg"
