- title: "Armband bred rem"
  image: "/images/products/armband-bred-rem.jpg"
  image_thumbnail: "/images/products/armband-bred-rem-thumbnail.jpg"
  category_id: "1"

- title: "Armband bred special"
  image: "/images/products/armband-bred-special.jpg"
  image_thumbnail: "/images/products/armband-bred-special-thumbnail.jpg"
  category_id: "1"

- title: "Armband flätat"
  image: "/images/products/armband-flatat.jpg"
  image_thumbnail: "/images/products/armband-flatat-thumbnail.jpg"
  category_id: "1"

- title: "Bälte klassiskt"
  image: "/images/products/balte-klassiskt.jpg"
  image_thumbnail: "/images/products/balte-klassiskt-thumbnail.jpg"
  category_id: "2"

- title: "Bälte special"
  image: "/images/products/balte-special.jpg"
  image_thumbnail: "/images/products/balte-special-thumbnail.jpg"
  category_id: "2"

- title: "Handväska rak"
  image: "/images/products/handvaska-rak.jpg"
  image_thumbnail: "/images/products/handvaska-rak-thumbnail.jpg"
  category_id: "4"

- title: "Handväska rundad"
  image: "/images/products/handvaska-rundad.jpg"
  image_thumbnail: "/images/products/handvaska-rundad-thumbnail.jpg"
  category_id: "4"

- title: "Kreditkortshållare"
  image: "/images/products/kreditkortshallare.jpg"
  image_thumbnail: "/images/products/kreditkortshallare-thumbnail.jpg"
  category_id: "5"

- title: "Mobilfodral för bälte"
  image: "/images/products/mobilfodral-for-balte.jpg"
  image_thumbnail: "/images/products/mobilfodral-for-balte-thumbnail.jpg"
  category_id: "3"

- title: "Nyckelfodral"
  image: "/images/products/nyckelfodral.jpg"
  image_thumbnail: "/images/products/nyckelfodral-thumbnail.jpg"
  category_id: "3"

- title: "Plånbok stor"
  image: "/images/products/planbok-stor.jpg"
  image_thumbnail: "/images/products/planbok-stor-thumbnail.jpg"
  category_id: "5"

- title: "Träsko klassisk"
  image: "/images/products/trasko-klassisk.jpg"
  image_thumbnail: "/images/products/trasko-klassisk-thumbnail.jpg"
  category_id: "6"
